name: Build and deploy Node.js app to Azure Web App - SwiftCV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '~22'

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install backend dependencies
        run: npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F7D8E82880F348968EBEA6BBB01CD8DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_808126D61F6842A7A9B7F9CAC20721EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4EC62FD3FFFC46AD91AFDB63A9F65C9A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SwiftCV'
          slot-name: 'Production'
          package: .
